-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06-11-2020 18:22:19
-- Server version: 5.5.5-10.3.24-MariaDB-1:10.3.24+maria~focal
-- Client version: 4.1

USE challenyou;

CREATE TABLE challenge (
  challengeId int(11) NOT NULL AUTO_INCREMENT,
  challengeDate datetime NOT NULL DEFAULT 'current_timestamp()',
  challengeName varchar(255) NOT NULL,
  PRIMARY KEY (challengeId)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE Level (
  levelId int(11) NOT NULL AUTO_INCREMENT,
  levelDate datetime NOT NULL DEFAULT 'current_timestamp()',
  levelSublevel int(11) NOT NULL,
  levelName varchar(50) NOT NULL,
  PRIMARY KEY (levelId)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE queueWhat (
  queueWhatId int(11) NOT NULL AUTO_INCREMENT,
  queueWhatDate datetime NOT NULL DEFAULT 'current_timestamp()',
  queueWhatName varchar(50) NOT NULL,
  PRIMARY KEY (queueWhatId)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE tag (
  tagId int(11) NOT NULL AUTO_INCREMENT,
  tagDate datetime NOT NULL DEFAULT 'current_timestamp()',
  tagName varchar(50) NOT NULL,
  PRIMARY KEY (tagId)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE users (
  userId int(11) NOT NULL AUTO_INCREMENT,
  userDate datetime NOT NULL DEFAULT 'current_timestamp()',
  userNickName varchar(50) NOT NULL,
  userName varchar(60) NOT NULL,
  userLastName varchar(60) NOT NULL,
  userPassword varchar(60) NOT NULL,
  userEmail varchar(60) DEFAULT 'NULL',
  userIdFacebook varchar(100) DEFAULT 'NULL',
  userIdGoogle varchar(100) DEFAULT 'NULL',
  userIdApple varchar(100) DEFAULT 'NULL',
  userIdTwitter varchar(100) DEFAULT 'NULL',
  userIdTiktok varchar(100) DEFAULT 'NULL',
  userIdGithub varchar(100) DEFAULT 'NULL',
  userRankTotal int(11) NOT NULL DEFAULT 0,
  userRankPromedio int(11) NOT NULL DEFAULT 0,
  userLevelId int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (userId),
  CONSTRAINT users_fk0 FOREIGN KEY (userLevelId)
  REFERENCES Level (levelId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE historyLine (
  historyId int(11) NOT NULL AUTO_INCREMENT,
  historyDate datetime NOT NULL DEFAULT 'current_timestamp()',
  userId int(11) NOT NULL,
  historyRank int(11) NOT NULL,
  historyVideo varchar(255) NOT NULL,
  PRIMARY KEY (historyId),
  CONSTRAINT historyLine_fk0 FOREIGN KEY (userId)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE queue (
  queueId int(11) NOT NULL AUTO_INCREMENT,
  queueDate datetime NOT NULL DEFAULT 'current_timestamp()',
  userId int(11) NOT NULL,
  queueWhatId int(11) NOT NULL,
  queueIdWhat int(11) NOT NULL,
  PRIMARY KEY (queueId),
  CONSTRAINT queue_fk0 FOREIGN KEY (userId)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT queue_fk1 FOREIGN KEY (queueWhatId)
  REFERENCES queueWhat (queueWhatId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE rankingConsolidate (
  rankingConsolidateId int(11) NOT NULL AUTO_INCREMENT,
  rankingConsolidateDate datetime NOT NULL DEFAULT 'current_timestamp()',
  challengeId int(11) NOT NULL,
  userId int(11) NOT NULL,
  PRIMARY KEY (rankingConsolidateId),
  UNIQUE INDEX UK_rankingConsolidate_challeng (challengeId),
  UNIQUE INDEX UK_rankingConsolidate_userId (userId),
  CONSTRAINT FK_challenge_rankingConsolidate_challengeId FOREIGN KEY (challengeId)
  REFERENCES challenge (challengeId) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT FK_users_rankingConsolidate_userId FOREIGN KEY (userId)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE userFollow (
  userFollowId int(11) NOT NULL AUTO_INCREMENT,
  userFollowDate datetime NOT NULL DEFAULT 'current_timestamp()',
  userId int(11) NOT NULL COMMENT 'usuario original',
  userIdFollow int(11) NOT NULL COMMENT 'usuario que sigue',
  PRIMARY KEY (userFollowId),
  UNIQUE INDEX UK_userFollow_userId (userId),
  UNIQUE INDEX UK_userFollow_userIdFollow (userIdFollow),
  CONSTRAINT FK_users_userFollow_userId FOREIGN KEY (userId)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT FK_users_userFollow_userIdFollow FOREIGN KEY (userIdFollow)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE comments (
  commentId int(11) NOT NULL AUTO_INCREMENT,
  commentDate datetime NOT NULL DEFAULT 'current_timestamp()',
  historyId int(11) NOT NULL,
  commentTexto varchar(255) DEFAULT '''NULL''',
  PRIMARY KEY (commentId),
  UNIQUE INDEX UK_comments_historyId (historyId),
  CONSTRAINT FK_historyLine_comments_historyId FOREIGN KEY (historyId)
  REFERENCES historyLine (historyId) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE historyChallenge (
  historyChallengeId int(11) NOT NULL AUTO_INCREMENT,
  historyChallengeDate datetime NOT NULL DEFAULT 'current_timestamp()',
  historyID int(11) NOT NULL,
  challengeId int(11) NOT NULL,
  PRIMARY KEY (historyChallengeId),
  CONSTRAINT historyChallenge_fk0 FOREIGN KEY (historyID)
  REFERENCES historyLine (historyId) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT historyChallenge_fk1 FOREIGN KEY (challengeId)
  REFERENCES challenge (challengeId) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE historyTag (
  historyTagId int(11) NOT NULL AUTO_INCREMENT,
  historyTagDate datetime NOT NULL DEFAULT 'current_timestamp()',
  historyId int(11) NOT NULL,
  tagId int(11) NOT NULL,
  PRIMARY KEY (historyTagId),
  CONSTRAINT historyTag_fk0 FOREIGN KEY (historyId)
  REFERENCES historyLine (historyId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT historyTag_fk1 FOREIGN KEY (tagId)
  REFERENCES tag (tagId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE ranking (
  rankId int(11) NOT NULL AUTO_INCREMENT,
  rankDate datetime NOT NULL DEFAULT 'current_timestamp()',
  historyID int(11) NOT NULL,
  userId int(11) NOT NULL,
  historyChallengeId int(11) NOT NULL,
  rank int(11) NOT NULL,
  rankProcessUser tinyint(1) NOT NULL DEFAULT 0,
  rankProcessConsolidate tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (rankId),
  CONSTRAINT ranking_fk0 FOREIGN KEY (historyID)
  REFERENCES historyLine (historyId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ranking_fk1 FOREIGN KEY (userId)
  REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ranking_fk2 FOREIGN KEY (historyChallengeId)
  REFERENCES historyChallenge (historyChallengeId) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;